using UnityEngine;
using UnityEngine.UI;
using TMPro;
using UnityEngine.SceneManagement;
using System.Collections.Generic;
using System.Linq.Expressions;

public class StageController : MonoBehaviour
{

    public GameObject transitionPrefab;
    public SpriteRenderer lifeBarRenderer;       // ì¦‰ì‹œ ë°˜ì˜ë˜ëŠ” ê²Œì´ì§€
    public SpriteRenderer lifeBarTempRenderer;   // ëŠë¦¬ê²Œ ë”°ë¼ì˜¤ëŠ” ê²Œì´ì§€
    public TMP_Text scoreText;
    public TMP_Text targetScoreText;
    public TMP_Text stageText;

    public GameObject canvasResult;
    public GameObject canvasWin;
    public GameObject canvasLose;
    public GameObject canvasNick;
    public Button btnNextStage;                  // â† ì—¬ê¸° ì¶”ê°€ (ì¸ìŠ¤í™í„° ì—°ê²°ìš©)


    public GameObject playerPrefab;

    private int maxLife = 10000;
    private bool resultShown = false;

    public bool cloudMode = false;
    private int cloudTimer = 0;
    public GameObject cloudPrefab;

    [Header("ë¸Œë ˆì´ì»¤ ê´€ë ¨")]
    public GameObject breakerPrefab;   // <- ì¸ìŠ¤í™í„°ì—ì„œ scr_breakerController í”„ë¦¬íŒ¹ ì—°ê²°
    public bool breakerMode = false;
    [Header("ì‹ í˜¸ë“± ëª¨ë“œ ê´€ë ¨")]
    public bool trafficLightMode = false;
    public int[] trafficLightLine = new int[] { 0, 0, 0 };

    [Header("ì‹ í˜¸ë“± ëª¨ë“œ ê´€ë ¨")]
    public bool rushHourMode = false;

    public bool infiniteMode = false;
    public int infiniteModeTargetScore = 1500;
    public int infiniteModeStage = 1;
    public GameObject infiniteModeLevelupPrefab;


    //ë¬´í•œëª¨ë“œ ì‹œìŠ¤í…œ ê´€ë ¨
    int[] result = new int[4];       // 0~3 ìë¦¬, ê¸°ë³¸ì€ 0
    int[] prevResult = new int[4];   // ì´ì „ ìƒíƒœ ì €ì¥ìš©

    void Start()
    {
        SoundManager.Instance.PlayBGM("Ingame");
        StageBalanceSetting();
        InfiniteBalanceSetting();
        global.isGameOver = 0;
        GameManager.Instance.life = 10000;
        GameManager.Instance.score = 0;

        if (lifeBarRenderer == null)
            Debug.LogError("lifeBarRendererê°€ ì—°ê²°ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.");

        if (lifeBarTempRenderer == null)
            Debug.LogError("lifeBarTempRendererê°€ ì—°ê²°ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.");

        if (btnNextStage == null)
            Debug.LogError("btnNextStage ë²„íŠ¼ì´ ì—°ê²°ë˜ì§€ ì•Šì•˜ìŠµë‹ˆë‹¤.");

        if (canvasResult != null) canvasResult.SetActive(false);
        if (canvasWin != null) canvasWin.SetActive(false);
        if (canvasLose != null) canvasLose.SetActive(false);
        if (canvasNick != null) canvasNick.SetActive(false);


        targetScoreText.text = $"TargetScore : {GameManager.Instance.GetTargetScore()}";
    }


    void Update()
    {
        //---------------------------------------------------------------
        //DEBUG FUNCTION
        //---------------------------------------------------------------
        /*
        if (Input.GetKeyDown(KeyCode.I))
        {
            global.StageMap += 1;
            if (global.StageMap>2)
            {
                global.StageMap = 0;
            }
        }*/

        if (Input.GetKeyDown(KeyCode.P))
        {
            global.carSpeed += 1;
        }
        if (Input.GetKeyDown(KeyCode.O))
        {
            global.carSpeed -= 1;
        }

        if (Input.GetKeyDown(KeyCode.S))
        {
            GameManager.Instance.AddLife(-500);
        }
        /*
        if (Input.GetKeyDown(KeyCode.S))
        {
            GameManager.Instance.AddLife(200000);
        }
        */
        if (Input.GetKeyDown(KeyCode.D))
        {
            GameManager.Instance.AddScore(500);
        }

        if (Input.GetKeyDown(KeyCode.C))
        {
            if (cloudMode == false) { cloudMode = true; } else { cloudMode = false; }
            cloudTimer = 1300;
            Debug.Log("CloudMode" + cloudMode);
        }

        if (Input.GetKeyDown(KeyCode.N))
        {
            rushHourMode = !rushHourMode;
            Debug.Log("rushHour Mode: " + rushHourMode);
        }

        if (Input.GetKeyDown(KeyCode.B))
        {
            trafficLightMode = !trafficLightMode;
            Debug.Log("TrafficLight Mode: " + trafficLightMode);

            if (trafficLightMode)
            {
                trafficLightLine = new int[] { 1, 2, 3 };
                /*
                // 1, 2, 3 ë°°ì—´ ë§Œë“¤ê³  ëœë¤ ìˆœì„œë¡œ ì„ê¸° (ê°„ë‹¨ ë²„ì „)
                int[] nums = { 1, 2, 3 };
                for (int i = 0; i < nums.Length; i++)
                {
                    int rand = Random.Range(0, nums.Length);
                    int temp = nums[i];
                    nums[i] = nums[rand];
                    nums[rand] = temp;
                }
                trafficLightLine = nums;*/
            }
            else
            {
                trafficLightLine = new int[] { 0, 0, 0 };
            }

        }

        if (Input.GetKeyDown(KeyCode.V))
        {
            breakerMode = !breakerMode;
            Debug.Log("Breaker Mode: " + breakerMode);
        }

        //---------------------------------------------------------------



        if (cloudMode == true)
        {
            cloudTimer += 1;
            if (cloudTimer > 600)
            {
                cloudTimer = 0;
                for (var i = 0; i < 2; i++)
                {
                    Vector3 spawnPos = new Vector3(12f + i * 4, Random.Range(-4f, 0f), 0f);
                    Instantiate(cloudPrefab, spawnPos, Quaternion.identity);
                }
                Debug.Log("Cloud Created!!!");
                cloudTimer = 0;
            }
        }



        // ğŸ”¹ breaker ëª¨ë“œì¼ ë•Œ ëœë¤ ìƒì„± ì‹œë„
        if (breakerMode)
        {
            int rand = Random.Range(1, 201); // 1~200
            if (rand == 1)
            {
                SpawnBreaker();
            }
        }


        if (GameManager.Instance.GetLife() > maxLife)
        {
            GameManager.Instance.SetLife(maxLife);
        }
        if (GameManager.Instance == null) return;



        GameStageBlockController controller = FindObjectOfType<GameStageBlockController>();
        if (controller != null)
        {
            if (controller.infiniteModeDelay == false)
            {
                GameManager.Instance.AddLife(-1);
            }
        }


        float life = Mathf.Clamp(GameManager.Instance.GetLife(), 0, maxLife);

        // ì¦‰ì‹œ ë°˜ì˜ ê²Œì´ì§€
        if (lifeBarRenderer != null)
        {
            Vector3 scale = lifeBarRenderer.transform.localScale;
            scale.x = (life * 86f) / maxLife;
            lifeBarRenderer.transform.localScale = scale;
        }

        // ëŠë¦¬ê²Œ ë”°ë¼ì˜¤ëŠ” ê²Œì´ì§€
        if (lifeBarTempRenderer != null && lifeBarRenderer != null)
        {
            Vector3 current = lifeBarTempRenderer.transform.localScale;
            float targetX = lifeBarRenderer.transform.localScale.x;
            current.x += (targetX - current.x) / 30f;
            lifeBarTempRenderer.transform.localScale = current;
        }

        if (scoreText != null)
        {
            scoreText.text = $"{GameManager.Instance.GetScore()}";
        }


        /*
        {
            GameManager.Instance.AddLife(-500);
        }*/





        //ë¬´í•œëª¨ë“œ ëª©í‘œì ìˆ˜ ë„ë‹¬
        if (infiniteMode == true)
        {
            if (GameManager.Instance.GetScore() >= infiniteModeTargetScore )
            {
                
                infiniteModeStage += 1;
                Debug.Log("ìŠ¤í…Œì´ì§€ ë ˆë²¨ì—…" + infiniteModeStage);
                InfiniteBalanceSetting();
                //Instantiate(infiniteModeLevelupPrefab);


                //GameStageBlockController controller = FindObjectOfType<GameStageBlockController>();
                if (controller != null)
                {
                    controller.infiniteModeDelay = true;
                    controller.FunctionDestoryBlock();
                    controller.DestroyPreviewBlock();
                    /*
                        ìœ„ì— ì´ë™í•˜ëŠ” ì°¨ëŠ” ì œê±°ë˜ëŠ”ë°, ì„¤ì¹˜í•œ ì°¨ëŸ‰ê³¼ ê·¸ëŸ°ê±´ ì•ˆì§€ì›Œì§
                        ëŠ˜ ê·¸ë¬ë˜ê²ƒì²˜ëŸ¼ ì‹œê°„ì§€ë‚˜ë©´ ë‹¤ì‹œ ìë™ì°¨ ë“±ì¥í•¨. ìë™ì°¨ ì•ˆë©ˆì·„ìŒ.
                     */
                    Debug.Log("í•´ë‹¹ ì½”ë“œ ì‘ë™ ì™„ë£Œ");
                }


                /*
                    íŠ¸ë Œì§€ì…˜ì—°ì¶œ, ì—¬ê¸°ì„œ global.StageMapë„ ê°™ì´ ë°”ê¾¸ì…ˆ
                    Instantiate(transitionPrefab);
                    ì €ê²ƒ.isRealMove = false;
                    ì´ëŸ¬ë©´ ê·¸ëƒ¥ ë‚˜ì™”ë‹¤ê°€ ì•„ë¬´ê²ƒë„ ì•ˆí•˜ê³  ì‚¬ë¼ì§€ê² ì§€.
                    í™”ë©´ ê°€ë¦¬ëŠ”ë™ì•ˆ ì¤‘ìš”í•œê±° ì«™ ì³ë‚´ê³ .
                */

                FoldTransition transition = Instantiate(transitionPrefab).GetComponent<FoldTransition>();
                transition.isRealMove = false;

                cloudMode = false;
                breakerMode = false;
                trafficLightMode = false;
                rushHourMode = false;

                
                Invoke("InfiniteModeDestroy", 0.7f);
                Invoke("InfiniteModeRestart", 2f);


                // ##### 2025 - 10 - 28 ####
                //invoke ì‚¬ìš©í•´ì„œ RealStart ë„ 1ë¡œ í’€ì–´ì£¼ê³ , ëª¨ë“œë„ ëœë¤ì„¸íŒ…í•˜ëŠ”ê±° ì¶”ê°€
            }
        }




        //ì¼ë°˜ëª¨ë“œ ëª©í‘œ ì ìˆ˜ ë„ë‹¬
        if (infiniteMode == false)
        {
            if (GameManager.Instance.GetScore() >= GameManager.Instance.targetScore && global.stageNow < 50)
            {
                GameManager.Instance.AddLife(-10000);
            }
        }




        if (!resultShown && GameManager.Instance.GetLife() <= 0)
        {
            resultShown = true;
            global.isGameOver = 1;

           


            if (canvasResult != null)
            {

                if (global.stageNow == 100)
                {
                    if (canvasNick != null)
                    {
                        canvasNick.SetActive(true);
                        //global.stage += 1;
                    }
                }
                else
                {
                    if (GameManager.Instance.GetScore() >= GameManager.Instance.targetScore)
                    {
                        if (canvasWin != null)
                        {
                            canvasWin.SetActive(true);
                        }
                        if (btnNextStage != null)
                        {
                            btnNextStage.interactable = true;
                        }
                        global.stage += 1;

                        PlayerFSM PlayerScr = playerPrefab.GetComponent<PlayerFSM>();
                        if (PlayerScr != null)
                        {
                            PlayerScr.HighScore(); //B.cs ì•ˆì˜ C í•¨ìˆ˜ í˜¸ì¶œ
                        }
                    }
                    else
                    {
                        if (canvasLose != null)
                        {
                            canvasLose.SetActive(true);
                        }
                        if (btnNextStage != null)
                        {
                            btnNextStage.interactable = false;
                        }
                        PlayerFSM PlayerScr = playerPrefab.GetComponent<PlayerFSM>();
                        if (PlayerScr != null)
                        {
                            PlayerScr.GameOver(); //B.cs ì•ˆì˜ C í•¨ìˆ˜ í˜¸ì¶œ
                        }


                    }
                    canvasResult.SetActive(true);
                }
            }
        }
    }

    void InfiniteModeDestroy()
    {
        GameStageBlockController controller = FindObjectOfType<GameStageBlockController>();
        if (controller != null)
        {
            controller.ResetAllBlocks();
        }
        global.StageMap += 1;
        if (global.StageMap > 2)
        {
            global.StageMap = 0;
        }
        InfiniteModeShuffle();
    }

    void InfiniteModeRestart()
    {


       


        GameStageBlockController controller = FindObjectOfType<GameStageBlockController>();
        if (controller != null)
        {
            controller.infiniteModeDelay = false;
        }



    }
    /*
     ButtonSystem
     */
    public void ButtonNext_Click()
    {
        //SceneManager.LoadScene("Scene_Title");
        Scene currentScene = SceneManager.GetActiveScene();
        SceneManager.LoadScene(currentScene.name);
        /*
        global.mapChange = "Scene_StageSelect";
        if (!string.IsNullOrEmpty(global.mapChange)) {Instantiate(transitionPrefab);}*/
    }
    public void ButtonStage_Click()
    {
      //  SceneManager.LoadScene("Scene_StageSelect");

        global.mapChange = "Scene_StageSelect";
        if (!string.IsNullOrEmpty(global.mapChange)) { Instantiate(transitionPrefab); }

    }
    public void ButtonRestart_Click()
    {
        //SceneManager.LoadScene("Scene_Title");
        Scene currentScene = SceneManager.GetActiveScene();
        //SceneManager.LoadScene(currentScene.name);

        global.mapChange = currentScene.name;
        if (!string.IsNullOrEmpty(global.mapChange)) { Instantiate(transitionPrefab); }

    }

    public void OnClickRank()
    {
//        SaveScore();
    }


    public void InfiniteModeShuffle()
    {
        // ì´ˆê¸°í™”
        for (int i = 0; i < 4; i++)
            result[i] = 0;

        int activeCount = 0;

        // ë‹¨ê³„ë³„ë¡œ í™œì„± ê°œìˆ˜ ê²°ì •
        if (infiniteModeStage >= 10) activeCount = 3;
        else if (infiniteModeStage >= 5) activeCount = 2;
        else if (infiniteModeStage >= 3) activeCount = 1;

        // activeCount ê°€ 0ì´ë©´ ì•„ë¬´ê²ƒë„ ì•ˆ ì¼¬
        if (activeCount == 0)
        {
            SavePrevResult();
            return;
        }

        // ê°™ì€ ì¡°í•©ì´ ë°˜ë³µë˜ì§€ ì•Šë„ë¡ ë£¨í”„
        bool isSame = true;
        int safety = 0;

        while (isSame && safety < 100)
        {
            safety++;

            // ëœë¤í•˜ê²Œ uniqueí•œ index ì„ íƒ
            List<int> indices = new List<int> { 0, 1, 2, 3 };
            for (int i = 0; i < activeCount; i++)
            {
                int r = Random.Range(0, indices.Count);
                int idx = indices[r];
                result[idx] = 1;
                indices.RemoveAt(r);
            }

            // ì´ì „ê³¼ ë™ì¼í•œì§€ ì²´í¬
            isSame = AreSame(result, prevResult);

            // ê°™ìœ¼ë©´ ë‹¤ì‹œ ì´ˆê¸°í™”í•˜ê³  ì¬ì‹œë„
            if (isSame)
            {
                for (int i = 0; i < 4; i++)
                    result[i] = 0;
            }
        }

        SavePrevResult();

        if (result[0] == 1) { cloudMode = true; cloudTimer = 1300; }
        if (result[1] == 1) { trafficLightMode = true; trafficLightLine = new int[] { 1, 2, 3 }; }
        if (result[2] == 1) { breakerMode = true; }
        if (result[3] == 1) { rushHourMode = true; }
        

        if (rushHourMode==true)
        {
            global.carSpawnSpeed = infiniteModeStage / 15;
        }

        // ë””ë²„ê·¸ ì¶œë ¥ìš©
        Debug.Log($"[Stage {infiniteModeStage}] ê²°ê³¼: {string.Join(",", result)}");
    }

    bool AreSame(int[] a, int[] b)
    {
        for (int i = 0; i < a.Length; i++)
        {
            if (a[i] != b[i]) return false;
        }
        return true;
    }

    void SavePrevResult()
    {
        for (int i = 0; i < 4; i++)
            prevResult[i] = result[i];
    }







    void InfiniteBalanceSetting()
    {
        if (infiniteMode == true)
        {
            infiniteModeTargetScore = 1200 + (infiniteModeStage - 1) * 1200 + infiniteModeStage * 300;
            global.carSpeed = 5 + infiniteModeStage * 0.3f;
        }
        /*
            ì—¬ê¸°ì„œ ëœë¤í•˜ê²Œ ëª¨ë“œ ì‹¤í–‰í•˜ë©´ ë¨
            ìŠ¤í…Œì´ì§€ 1ì—ì„œ 3ê¹Œì§€ëŠ” ë­ì—†ê²Œ
            3,4,5,6ê¹Œì§€ëŠ” 1ê°€ì§€
            7,8,9,10 ê¹Œì§€ëŠ” 2ê°€ì§€
            11ë¶€í„° 3ê°€ì§€ ì¤‘ì²©ë  ìˆ˜ ìˆë„ë¡ ì„¸íŒ….

            ë˜í•œ ì—¬ê¸°ì„œ ë§µ ë°°ê²½ ë°”ë€ŒëŠ” ê°€ë²¼ìš´ ì—°ì¶œ ìˆì—ˆìœ¼ë©´ ì¢‹ê² ëŠ”ë°, íƒœê³ ì˜ë‹¬ì¸? ë¶ë„ë¦¬ ë˜‘ë˜‘! í•˜ê³  íœ™ ë„˜ê²¨ì§€ë©´ì„œ ë°°ê²½ë°”ë€Œê³  ìŠ¤í”¼ë“œì—… ì—°ì¶œë‚˜ì˜¤ëŠ”ë“¯ì´?
            ëŸ¬ì‰¬ì•„ì›Œ ë„ë©´ ë°”ë¡œ ìƒˆê±°ë‚˜ì˜¤ë‚˜? ì´ìƒì—†ê²Œ, ëŸ¬ì‰¬ì•„ì›Œ ë„ë©´ ìˆëŠ”ê±° ë‹¤ ì‚¬ë¼ì§„ ë‹¤ìŒì— spawn ë˜ê²Œ í•˜ë©´ ì¢‹ê² ë„¤.
        */
    }

    void StageBalanceSetting()
    {
        if (infiniteMode == false)
        {

            int dayInCycle = (global.stageNow - 1) % 5 + 1;
            switch (dayInCycle)
            {
                case 1:
                case 2:
                    global.StageMap = 0;
                    break;
                case 3:
                    global.StageMap = 1;
                    break;
                case 4:
                    global.StageMap = 2;
                    break;
                case 5:
                    global.StageMap = 0;
                    break;
            }


            // ê¸°ë³¸ê°’
            GameManager.Instance.targetScore = 1600 + global.stageNow * 400;
            global.carSpeed = 4 + (global.stageNow*0.3f);
            global.carSpawnSpeed = 1 - (global.stageNow - 1) * 0.04f;
            stageText.text = global.stageNow + "ì¼ì°¨";

            // 1ë²ˆì§¸ ê¸ˆìš”ì¼ : ì•ˆê°œ
            if (global.stageNow == 5)
            {
                stageText.text = global.stageNow + "ì¼ì°¨ (êµ¬ë¦„)";
                cloudMode = true;
                cloudTimer = 1300;
            }
            // 2ë²ˆì§¸ ê¸ˆìš”ì¼ : ìƒ‰ê¹” ì°¨ëŸ‰ ë‹¨ì†
            else if (global.stageNow == 10)
            {
                stageText.text = global.stageNow + "ì¼ì°¨ (ì‹ í˜¸ë“±)";
                trafficLightMode = true;
                trafficLightLine = new int[] { 1, 2, 3 };
            }
            // 3ë²ˆì§¸ ê¸ˆìš”ì¼ : ì²­ì†Œì°¨
            else if (global.stageNow == 15)
            {
                stageText.text = global.stageNow + "ì¼ì°¨ (ì²­ì†Œì°¨)";
                breakerMode = true;
            }
            // 4ë²ˆì§¸ ê¸ˆìš”ì¼ : ëŸ¬ì‰¬ ì•„ì›Œ
            else if (global.stageNow == 20)
            {
                global.carSpeed = 5;
                stageText.text = global.stageNow + "ì¼ì°¨ (ëŸ¬ì‰¬ì•„ì›Œ)";
                rushHourMode = true;
            }
            // ë¬´í•œëª¨ë“œ ê¸°ë³¸ ì„¸íŒ…
            else if (global.stageNow == 100)
            {
                GameManager.Instance.targetScore = 999999999;
                global.carSpeed = 5;
                global.carSpawnSpeed = 1;
                stageText.text = "ë¬´í•œëª¨ë“œ";
                infiniteMode = true;
            }
        }

    }


    void SpawnBreaker()
    {
        // ğŸ”’ ì´ë¯¸ ë¸Œë ˆì´ì»¤ê°€ ì¡´ì¬í•˜ë©´ ìƒˆë¡œ ì†Œí™˜í•˜ì§€ ì•ŠìŒ
        if (FindObjectOfType<scr_breakerController>() != null)
            return;

        int lineNum = Random.Range(1, 13); // 1~12 ì¤‘ í•˜ë‚˜
        Vector3 spawnPos = GetLinePosition(lineNum);

        GameObject obj = Instantiate(breakerPrefab, spawnPos, Quaternion.identity);
        scr_breakerController breaker = obj.GetComponent<scr_breakerController>();
        if (breaker != null)
        {
            breaker.targetLine = lineNum;
        }

        Debug.Log($"[Breaker] ë¼ì¸ {lineNum} ì†Œí™˜ë¨");
    }


    // ğŸ”¹ ì„¼ì„œ ì²«ë²ˆì§¸ ì¤„ì˜ ë¼ì¸ë³„ ìœ„ì¹˜ ë°˜í™˜ (ê°€ì§œ ì˜ˆì‹œ, ë„¤ ì¢Œí‘œì— ë§ê²Œ ìˆ˜ì •)
    // ë¼ì¸ ë²ˆí˜¸(1~12)ì— ë§ì¶° ì‹¤ì œ ê·¸ë¦¬ë“œ ê¸°ì¤€ Xì¢Œí‘œ ë°˜í™˜
    Vector3 GetLinePosition(int lineIndex)
    {
        // ë¼ì¸ ì¸ë±ìŠ¤ ë³´ì •
        int index = lineIndex - 1;

        // ê° 4x4 ê·¸ë¦¬ë“œì˜ êµ¬ê°„ êµ¬ë¶„
        int gridIndex = index / 4;     // 0, 1, 2 ì¤‘ í•˜ë‚˜
        int localX = index % 4;        // ê° 4x4 ë‚´ë¶€ Xì¢Œí‘œ

        // GameStageBlockControllerì˜ íŒŒë¼ë¯¸í„°ì™€ ë™ì¼í•˜ê²Œ ë§ì¶¤
        float cellSize = 0.88f;
        float gridSpacingX = 0.68f;
        float gridOriginOffsetX = -3f;

        // ğŸ¯ X ì¢Œí‘œ ê³„ì‚°
        float offsetX = gridIndex * (4 * cellSize + gridSpacingX);
        float worldX = gridOriginOffsetX + localX * cellSize + offsetX;

        // ğŸ¯ Y ì¢Œí‘œ ê³ ì • (ìš”ì²­ëŒ€ë¡œ)
        float worldY = -2f;

        return new Vector3(worldX, worldY, 0f);
    }



}